import Image from 'next/image'
import Link from 'next/link'
import { ArrowUpRight, CircleDot, Ear, Gauge, MapPin } from 'lucide-react'
import { getBusinessProfile } from '@/lib/business-profile'

export const metadata = { title: 'Về Tiến Đạt Audio', description: 'Tiến Đạt Audio — tư vấn và triển khai giải pháp âm thanh tại Quảng Ngãi.' }

export default async function AboutPage() {
  const profile = await getBusinessProfile()
  return (
    <div className="sonic-page pt-28 md:pt-36">
      <section className="sonic-container pb-16 md:pb-24"><p className="sonic-label">About / The listening practice</p><h1 className="sonic-title mt-5 max-w-5xl">Chúng tôi tin rằng âm thanh tốt làm cho một không gian trở nên có hồn.</h1><p className="sonic-copy mt-7 max-w-2xl">Tiến Đạt Audio là nơi những người yêu âm nhạc tìm thấy thiết bị phù hợp, lời giải thích rõ ràng và một cấu hình có thể sống cùng họ trong nhiều năm.</p></section>
      <section className="relative min-h-[480px] overflow-hidden border-y border-white/10"><Image src="/images/sonic-hero.png" alt="Không gian nghe nhạc" fill sizes="100vw" className="object-cover object-center opacity-60" /><div className="absolute inset-0 bg-gradient-to-r from-[#080808] via-[#080808]/45 to-[#080808]/20" /><div className="sonic-container relative flex min-h-[480px] items-end py-12"><div><p className="sonic-label">Listening is personal</p><p className="mt-4 max-w-md text-2xl font-semibold leading-tight tracking-[-0.04em] text-[#e5e2e1] md:text-4xl">Không có một hệ thống hoàn hảo cho tất cả mọi người. Chỉ có hệ thống đúng với bạn.</p></div></div></section>
      <section id="solutions" className="sonic-container py-16 md:py-24"><div className="grid gap-12 lg:grid-cols-[.8fr_1.2fr] lg:gap-20"><div><p className="sonic-label">01 / Cách chúng tôi làm việc</p><h2 className="sonic-title mt-5">Bắt đầu từ việc lắng nghe.</h2></div><div className="grid gap-8 sm:grid-cols-2">{[[Ear, 'Hiểu nhu cầu', 'Bạn nghe gì, trong không gian nào và âm thanh cần xuất hiện ra sao?'], [Gauge, 'Đo và phối ghép', 'Từ công suất, độ nhạy đến vị trí đặt — mọi lựa chọn đều có căn cứ.'], [CircleDot, 'Cân chỉnh', 'Một hệ thống chỉ hoàn thiện khi nó phản hồi đúng trong căn phòng thật.'], [MapPin, 'Đồng hành', 'Từ showroom đến lắp đặt, chúng tôi ở lại sau khi sản phẩm được giao.']].map(([Icon, title, copy]) => { const Component = Icon as typeof Ear; return <div key={title as string} className="border-t border-white/15 pt-5"><Component size={19} className="text-[#d4af37]" /><h3 className="mt-5 text-lg font-bold text-[#e5e2e1]">{title as string}</h3><p className="mt-3 text-sm leading-6 text-[#9ea2a2]">{copy as string}</p></div> })}</div></div></section>
      <section id="projects" className="border-y border-white/10 bg-[#0d0d0d] py-16 md:py-24"><div className="sonic-container grid gap-12 lg:grid-cols-[1.1fr_.9fr] lg:items-center lg:gap-20"><div><p className="sonic-label">02 / Dự án & không gian</p><h2 className="sonic-title mt-5">Âm thanh phải thuộc về nơi nó sống.</h2><p className="sonic-copy mt-6 max-w-xl">Gia đình, cafe acoustic, phòng karaoke hay sân khấu nhỏ — mỗi dự án là một bài toán về độ phủ, cảm xúc và sự ổn định.</p><div className="mt-8 grid gap-3 sm:grid-cols-3"><div className="border border-white/10 p-4"><p className="text-2xl font-bold text-[#d4af37]">10+</p><p className="mt-2 text-xs leading-5 text-[#858989]">năm trong ngành</p></div><div className="border border-white/10 p-4"><p className="text-2xl font-bold text-[#d4af37]">24/7</p><p className="mt-2 text-xs leading-5 text-[#858989]">hỗ trợ sau lắp đặt</p></div><div className="border border-white/10 p-4"><p className="text-2xl font-bold text-[#d4af37]">01</p><p className="mt-2 text-xs leading-5 text-[#858989]">điểm nghe tại Quảng Ngãi</p></div></div></div><div className="sonic-panel p-7 md:p-9"><p className="sonic-label">Showroom / Quảng Ngãi</p><h3 className="mt-5 text-2xl font-bold tracking-[-0.04em] text-[#e5e2e1]">Một cuộc hẹn để nghe sự khác biệt.</h3><p className="mt-5 text-sm leading-7 text-[#9ea2a2]">{profile.address.formatted}<br />{profile.businessHours.join(' / ')}</p><Link href="/contact" className="sonic-button sonic-button-gold mt-8">Đặt lịch trải nghiệm <ArrowUpRight size={16} /></Link></div></div></section>
      <section className="sonic-container py-16 md:py-24"><div className="border-l-2 border-[#d4af37] pl-6 md:pl-10"><p className="text-2xl font-semibold leading-tight tracking-[-0.04em] text-[#e5e2e1] md:max-w-4xl md:text-4xl">“Điều quan trọng không phải là hệ thống đắt nhất. Mà là hệ thống khiến bạn muốn ngồi xuống và nghe thêm một bài nữa.”</p><p className="mt-5 text-xs font-bold uppercase tracking-[0.15em] text-[#858989]">— Tiến Đạt Audio</p></div></section>
    </div>
  )
}
