import Image from 'next/image'
import Link from 'next/link'
import { ArrowUpRight } from 'lucide-react'
import { getCombos } from '@/lib/catalog'

export const metadata = { title: 'Giải pháp phối ghép — Tiến Đạt Audio', description: 'Các cấu hình âm thanh tham khảo cho gia đình, cafe và không gian chuyên nghiệp.' }

export default async function CombosPage() {
  const combos = await getCombos()
  return <div className="sonic-page pt-28 md:pt-36"><section className="sonic-container pb-16 md:pb-24"><p className="sonic-label">Systems / Curated setups</p><h1 className="sonic-title mt-5 max-w-4xl">Một cấu hình tốt là một câu chuyện được phối ghép.</h1><p className="sonic-copy mt-6 max-w-xl">Các bộ giải pháp chỉ là điểm tham khảo. Chúng tôi sẽ tinh chỉnh theo đúng không gian và cách bạn muốn sử dụng.</p></section><section className="border-y border-white/10 bg-[#0d0d0d] py-12 md:py-20"><div className="sonic-container grid gap-5 md:grid-cols-2">{combos.map((combo, index) => <Link key={combo.id} href={`/combos/${combo.slug}`} className="group relative min-h-[400px] overflow-hidden border border-white/10 bg-[#111111]"><Image src={combo.thumbnail.startsWith('http') || combo.thumbnail.startsWith('/uploads/') ? combo.thumbnail : '/images/sonic-hero.png'} alt={combo.title} fill sizes="(min-width: 768px) 50vw, 100vw" className="object-cover opacity-65 transition duration-700 group-hover:scale-105 group-hover:opacity-85" /><div className="absolute inset-0 bg-gradient-to-t from-[#080808] via-[#080808]/35 to-transparent" /><div className="absolute inset-x-6 bottom-6"><div className="flex items-end justify-between gap-4"><div><p className="sonic-label text-[#858989]">0{index + 1} / {combo.tags.join(' · ')}</p><h2 className="mt-3 text-3xl font-bold tracking-[-0.05em] text-[#e5e2e1]">{combo.title}</h2><p className="mt-3 max-w-md text-sm leading-6 text-[#c4c7c7]">{combo.description}</p></div><span className="flex h-10 w-10 shrink-0 items-center justify-center border border-white/30 text-[#e5e2e1] transition-all group-hover:border-[#d4af37] group-hover:bg-[#d4af37] group-hover:text-[#080808]"><ArrowUpRight size={17} /></span></div></div></Link>)}</div></section><section className="sonic-container py-16 md:py-24"><div className="border-l-2 border-[#d4af37] pl-6"><p className="text-2xl font-semibold leading-tight tracking-[-0.04em] text-[#e5e2e1] md:max-w-3xl md:text-4xl">Không có combo nào thay thế được một cuộc nghe thử trong căn phòng thật.</p><Link href="/contact" className="sonic-button sonic-button-gold mt-8">Tạo cấu hình riêng <ArrowUpRight size={16} /></Link></div></section></div>
}

