import Link from 'next/link'
import { ArrowUpRight, Package, Tags, Users } from 'lucide-react'
import { getDashboardStats, getProducts } from '@/lib/catalog'

export default async function AdminDashboardPage() {
  const [stats, products] = await Promise.all([getDashboardStats(), getProducts({ limit: 5 })])
  const cards = [[Package, 'Sản phẩm', stats.products, '/admin/products'], [Tags, 'Danh mục', stats.categories, '/admin/categories'], [Users, 'Yêu cầu mới', stats.leads, '/admin/contacts']]
  return <div className="mx-auto max-w-[1400px]"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="sonic-label">Dashboard / Overview</p><h1 className="mt-4 text-4xl font-bold tracking-[-0.06em]">Control room.</h1><p className="mt-3 text-sm text-[#858989]">Một cái nhìn nhanh về hệ thống Tiến Đạt Audio.</p></div><Link href="/" className="sonic-button sonic-button-ghost">Xem website <ArrowUpRight size={15} /></Link></div><div className="mt-10 grid gap-4 md:grid-cols-3">{cards.map(([Icon, label, value, href]) => { const Component = Icon as typeof Package; return <Link key={label as string} href={href as string} className="sonic-panel group p-6 transition-colors hover:border-[#d4af37]/60"><div className="flex items-start justify-between"><Component size={19} className="text-[#d4af37]" /><ArrowUpRight size={16} className="text-[#707474] transition-colors group-hover:text-[#d4af37]" /></div><p className="mt-9 text-4xl font-bold tracking-[-0.06em] text-[#e5e2e1]">{String(value).padStart(2, '0')}</p><p className="mt-2 text-xs font-bold uppercase tracking-[0.14em] text-[#858989]">{label as string}</p></Link> })}</div><div className="mt-10 grid gap-8 lg:grid-cols-[1.3fr_.7fr]"><section className="sonic-panel"><div className="flex items-center justify-between border-b border-white/10 px-6 py-5"><div><p className="sonic-label">Catalog / Recent</p><h2 className="mt-2 text-xl font-bold">Sản phẩm nổi bật</h2></div><Link href="/admin/products" className="text-xs font-bold uppercase tracking-[0.12em] text-[#d4af37]">Quản lý</Link></div><div>{products.map((product) => <Link key={product.id} href={`/san-pham/${product.slug}`} className="group flex items-center justify-between gap-4 border-b border-white/10 px-6 py-4 last:border-0"><div><p className="text-sm font-bold text-[#e5e2e1] group-hover:text-[#d4af37]">{product.name}</p><p className="mt-1 text-xs text-[#707474]">{product.brand} / {product.category}</p></div><span className="text-xs text-[#858989]">{product.inStock ? 'Đang bán' : 'Tạm ẩn'}</span></Link>)}</div></section><section className="sonic-panel p-6"><p className="sonic-label">Vận hành</p><h2 className="mt-3 text-2xl font-bold tracking-[-0.04em]">MongoDB ready.</h2><p className="mt-4 text-sm leading-6 text-[#9ea2a2]">Catalog hiện đọc MongoDB nếu có <code className="text-[#d4af37]">MONGODB_URI</code>, và tự fallback JSON khi local chưa cấu hình.</p><div className="mt-7 border-t border-white/10 pt-5 text-xs leading-6 text-[#707474]">Seed data: products, categories, brands, combos, posts, settings.</div></section></div></div>
}

