import Link from 'next/link'
import { ArrowUpRight } from 'lucide-react'
import { getGrowthDashboard } from '@/lib/analytics-repository'
import { deriveContentSEOInsights } from '@/lib/content-seo'
import { listContentPosts } from '@/lib/content-repository'
import { getSEOConfig } from '@/lib/seo-strategy'

export default async function SEODashboard() {
  const [growth, content, config] = await Promise.all([getGrowthDashboard(30), listContentPosts({ limit: 500 }), getSEOConfig()])
  const insights = deriveContentSEOInsights(config, content.items)
  const checklistGaps = content.items.filter((post) => post.status !== 'archived' && (!post.seo.metaTitle || !post.seo.metaDescription || !post.reviewer)).length
  const cards = [
    ['Published articles', content.items.filter((post) => post.status === 'published').length],
    ['Keyword uncovered', insights.uncoveredKeywords.length],
    ['Metadata gaps', checklistGaps],
    ['Article views / 30d', growth.articleViews],
    ['CTA conversion', `${growth.conversionRate}%`],
  ]
  return <div className="mx-auto max-w-[1400px] pb-20"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="sonic-label">SEO / Measurement / 30 days</p><h1 className="mt-4 text-4xl font-bold tracking-[-0.06em]">Visibility dashboard.</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-[#858989]">Chỉ hiển thị coverage và hành vi đã ghi nhận. Không dùng ranking score hoặc dữ liệu giả lập.</p></div><Link href="/admin/seo/strategy" className="sonic-button sonic-button-gold">Mở keyword map <ArrowUpRight size={15} /></Link></div><div className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-5">{cards.map(([label, value]) => <div key={String(label)} className="sonic-panel p-5"><p className="text-3xl font-bold">{String(value)}</p><p className="mt-2 text-xs uppercase tracking-[0.14em] text-[#858989]">{String(label)}</p></div>)}</div><div className="mt-8 grid gap-8 lg:grid-cols-2"><section className="sonic-panel p-6"><p className="sonic-label">Coverage gaps</p><h2 className="mt-3 text-2xl font-bold">Keyword cần content</h2><div className="mt-6 grid gap-3">{insights.uncoveredKeywords.length ? insights.uncoveredKeywords.map(({ keyword }) => <div key={keyword.id} className="flex items-center justify-between gap-4 border-t border-white/10 pt-3 text-sm"><span>{keyword.term}</span><span className="text-xs text-[#707474]">{keyword.targetPage}</span></div>) : <p className="text-sm text-[#858989]">Chưa có keyword orphan.</p>}</div></section><section className="sonic-panel p-6"><p className="sonic-label">Cannibalization</p><h2 className="mt-3 text-2xl font-bold">Cùng keyword, nhiều bài published</h2><div className="mt-6 grid gap-3">{insights.cannibalizedKeywords.length ? insights.cannibalizedKeywords.map(({ keyword, publishedPostIds }) => <p key={keyword.id} className="border-t border-white/10 pt-3 text-sm">{keyword.term}<span className="mt-1 block text-xs text-[#707474]">{publishedPostIds.length} bài — cần chọn URL chính</span></p>) : <p className="text-sm text-[#858989]">Chưa phát hiện cannibalization.</p>}</div></section></div><section className="sonic-panel mt-8 overflow-hidden"><div className="border-b border-white/10 px-6 py-5"><p className="sonic-label">Article performance</p><h2 className="mt-2 text-xl font-bold">Bài có lượt xem</h2></div>{growth.topArticles.length ? growth.topArticles.map((row) => { const post = content.items.find((item) => item.id === row.postId); return <div key={row.postId} className="flex items-center justify-between gap-4 border-b border-white/10 px-6 py-4 last:border-0"><div><p className="text-sm font-bold">{post?.title || row.postId}</p><p className="mt-1 text-xs text-[#707474]">{row.views} views · {row.ctas} CTA</p></div>{post && <Link href={`/kien-thuc/${post.slug}`} target="_blank" className="text-xs text-[#d4af37]">Xem bài</Link>}</div> }) : <p className="px-6 py-10 text-sm text-[#858989]">Chưa có event analytics trong 30 ngày gần nhất.</p>}</section></div>
}
